### ISSUE TITLE
sign and signup work proper, sent message , and it is storing in data base,  then socket is closing,  no response returning

### ISSUE THREAD

**Issue by shafa909** [danidee10/Chatire#12]
![Screenshot from 2019-10-11 21-34-38](https://user-images.githubusercontent.com/23289583/66666817-25ba4480-ec6f-11e9-927c-c0ef424ffdb0.png)

**Comment by shafa909** [comment]
uWSGI server was not running Properly .

**Comment by harshitexternlabs** [comment]
Can you explain what was the issue with uWSGI?
