### ISSUE TITLE
Logo proposal for Chatire

### ISSUE THREAD

**Issue by ihtiht** [danidee10/Chatire#3]
Hi,  i want to contribute to the still-developed Chatire project. I am a graphic designer. I noticed that Chatire has not yet got a logos. I think the best thing you can do is to design a logo.  I designed a logo without consulting you. I hope you like it.  If you do not like it or want to make changes, I can improve the logo. 

![de1b3749-d19d-40a7-8e74-89af1b231bd0](https://user-images.githubusercontent.com/36369736/39022702-7b49e74a-443f-11e8-9ee7-e6eb5d1d88db.jpg)

**Comment by danidee10** [comment]
Hi, @ihtiht Thanks for designing the logo! It looks great but I would love to change one thing. The colour scheme.

Blue is the primary colour of the interface. If you could include some blue in the design (e.g the orange part)

I'm not a graphic designer, so I don't know what's best :smile: but adding blue would make it match with the application.

Thanks!

**Comment by ihtiht** [comment]
Yes you are right. The blue color will be harmonious with the  theme. I made a few color variations. Which of the following do you like? 


![chatire11](https://user-images.githubusercontent.com/36369736/39084422-6f4d2958-457e-11e8-9da2-03e417ef7f79.jpg)

**Comment by danidee10** [comment]
I like number 3. Please open a PR with the logo. So I can include it

**Comment by ihtiht** [comment]
Do you also want to add it to the readme file? It will look like the following..


![gorunum](https://user-images.githubusercontent.com/36369736/39088680-00be76d6-45bf-11e8-9d4f-a6dcf45fa321.png)

**Comment by danidee10** [comment]
Yeah, that looks good!

**Comment by ihtiht** [comment]
Okay, i sent PR. Good work !
