### ISSUE TITLE
celery error

### ISSUE THREAD

**Issue by tiwo19** [danidee10/Chatire#8]
when i run server i  get this error  ModuleNotFoundError: No module named 'celery'

**Comment by aasmpro** [comment]
in the root directory of the project where `requirements.txt` exist, run this command to install all the requirements:
```
pip install -r requirements.txt
```
also 'celery' package could be installed by this command too:
```
pip install celery
```
note that:
1. if you use environments, activate them first.
2. the `pip` command could be `pip3` if you use GNU/Linux OSes.

**Comment by danidee10** [comment]
Thanks so much for clarifying @aasmpro 👍 
I will close this issue now.
