### ISSUE TITLE
data is defined but never used

### ISSUE THREAD

**Issue by Curti-s** [danidee10/Chatire#9]
In the signUp method in UserAuth.vue, "data" is passed as a param but never used.

![screenshot from 2019-03-02 04-51-58](https://user-images.githubusercontent.com/19207575/53675424-1e799400-3ca7-11e9-8603-47e7ce3e0eda.png)

**Comment by danidee10** [comment]
It's not a parameter, it's the response from the server but you're right it's never used.
It doesn't really affect anything :smile:  so I'll leave it like that (I don't want to risk breaking the app because there are no tests)

Thanks for spotting it :-)

**Comment by Curti-s** [comment]
I've actually used vue-cli 3 and you cannot get past it.

**Comment by Curti-s** [comment]
Many thanks btw for such a descriptive tut. 
God bless 🙏
